---
- name: Agent Installation
  hosts: all
  user: centos
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
  - name: install telnet
    package:
      name: telnet
      state: present          #absent     latest

  - name: Second task
    user:
      name: bob
      state: present

  - name: Add Admin Group
    group:
      name: admin
      state: present

  - name: Change file ownership, group and permissions
    file:
      path: /etc/foo.conf
      owner: root
      group: root
      mode: '0644'
      state: touch

