---
- name: Zip files
  hosts: all
  user: centos
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
  - name: Zip files over 90 days
    raw:  'find /var/log/ -type f  -name "*.log"  -mtime +90     -exec  gzip -v9  {}  +'